### ISSUE TITLE
Unable to launch on MacOS

### ISSUE THREAD

**Issue by DominikButz** [pyedifice/pyedifice#121]
I tried to play around with Edifice a bit on macOS. Seems it's still early days...
I tried to get the ToDo app from the pyedifice.org site running (without any change to the code). The first issues I ran into is that PySide6 and watchdog weren't installed automatically as a dependency. So I installed them. 

Next, the interpreter doesn't recognise edifice.Component:

  File "/..../Python/PyEdificeTest/main.py", line 5, in <module>
    class TodoApp(edifice.Component):
                  ^^^^^^^^^^^^^^^^^
AttributeError: module 'edifice' has no attribute 'Component'. Did you mean: 'component'?

That's a bummer. Any hints?

**Comment by jamesdbrock** [comment]
> I tried to play around with Edifice a bit on macOS. Seems it's still early days... I tried to get the ToDo app from the pyedifice.org site running (without any change to the code). The first issues I ran into is that PySide6 and watchdog weren't installed automatically as a dependency. So I installed them.

Yeah. Because `watchdog` is an optional development dependency for the hot-reloading feature. And Edifice supports both PySide6 and PyQt6 so you have to choose one. https://pyedifice.github.io/#poetry-build-system

> 
> Next, the interpreter doesn't recognise edifice.Component:
> 
> File "/..../Python/PyEdificeTest/main.py", line 5, in class TodoApp(edifice.Component): ^^^^^^^^^^^^^^^^^ AttributeError: module 'edifice' has no attribute 'Component'. Did you mean: 'component'?
> 
> That's a bummer. Any hints?

There is no longer any `edifice.Component`. Maybe you're looking at the old documentation website? https://www.pyedifice.org/
The new website is here. https://pyedifice.github.io/

I don't test Edifice on MacOS, so I'd like to hear more please about whether you can get it working.

**Comment by DominikButz** [comment]
OK, I got it - I was looking at the pyedifice.org indeed. Please add a link pointing to the new site and a remark that the site refers to an older version. Yes, the todo example app is running as expected now. Thanks
