### ISSUE TITLE
Markdown support for Label

### ISSUE THREAD

**Issue by masc-it** [pyedifice/pyedifice#189]
Hi,

Can we add markdown support for Label? It's pretty easy:

https://doc.qt.io/qt-5/qt.html#TextFormat-enum
https://stackoverflow.com/a/71308565/3337834

**Comment by masc-it** [comment]
Simple proposal:

```python
class MarkdownLabel(Label):
    def _initialize(self):
        super()._initialize()
        assert self.underlying is not None
        self.underlying.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
```

**Comment by jamesdbrock** [comment]
Good idea.

Maybe it should be a *prop* to the `Label` instead of a new Element?

https://github.com/pyedifice/pyedifice/blob/904c54d221bdc643baa0bb49598f87c1c11457f7/edifice/base_components/base_components.py#L477-L484

```python
text_format: QtCore.Qt.TextFormat = QtCore.Qt.TextFormat.AutoText
```

https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QLabel.html#PySide6.QtWidgets.QLabel.setTextFormat

**Comment by masc-it** [comment]
oh sure, that was just for illustration!

**Comment by jamesdbrock** [comment]
Done in v2.6.0 https://pyedifice.github.io/versions.html#v2-6-0
